// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTeWvXDKez-37I1USNtuRH-qVPEwhHUlA',
    appId: '1:639901049542:web:b034e05220da8a737f2dc7',
    messagingSenderId: '639901049542',
    projectId: 'zeroresiduos-50b37',
    authDomain: 'zeroresiduos-50b37.firebaseapp.com',
    storageBucket: 'zeroresiduos-50b37.firebasestorage.app',
    measurementId: 'G-HJFFZQEYFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0dcBSriJg9AKDMuX3qniIYamCt_fdAH0',
    appId: '1:639901049542:android:51b9676fafcfec287f2dc7',
    messagingSenderId: '639901049542',
    projectId: 'zeroresiduos-50b37',
    storageBucket: 'zeroresiduos-50b37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy4t6lZyvtIwztZ-6kkBVJx5u_8yqK2IQ',
    appId: '1:639901049542:ios:fec2e1375bfba8567f2dc7',
    messagingSenderId: '639901049542',
    projectId: 'zeroresiduos-50b37',
    storageBucket: 'zeroresiduos-50b37.firebasestorage.app',
    iosBundleId: 'com.example.zeroresiduos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy4t6lZyvtIwztZ-6kkBVJx5u_8yqK2IQ',
    appId: '1:639901049542:ios:fec2e1375bfba8567f2dc7',
    messagingSenderId: '639901049542',
    projectId: 'zeroresiduos-50b37',
    storageBucket: 'zeroresiduos-50b37.firebasestorage.app',
    iosBundleId: 'com.example.zeroresiduos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTeWvXDKez-37I1USNtuRH-qVPEwhHUlA',
    appId: '1:639901049542:web:0a23b3e90352603d7f2dc7',
    messagingSenderId: '639901049542',
    projectId: 'zeroresiduos-50b37',
    authDomain: 'zeroresiduos-50b37.firebaseapp.com',
    storageBucket: 'zeroresiduos-50b37.firebasestorage.app',
    measurementId: 'G-PJ2PKHCKJ2',
  );
}
